name: Eric Arellano
favicon: null
layout_spectrum: 0.6925017442554235
typography_spectrum: 0.8365208238828927
title: Eric Takes Mexico
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5980495535768569
  lightness: 0.8502225654665381
  saturation: 0.6261983532458544
  rhythmicContrast: 0.44295973470434546
purpose: []
